/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeusProjetosRouteImport } from './routes/meus-projetos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosNovoRouteImport } from './routes/projetos.novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusProjetosRoute = MeusProjetosRouteImport.update({
  id: '/meus-projetos',
  path: '/meus-projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ProjetosRoute,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/register': typeof RegisterRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/register': typeof RegisterRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/register': typeof RegisterRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/meus-projetos'
    | '/perfil'
    | '/projetos'
    | '/register'
    | '/projetos/$id'
    | '/projetos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/meus-projetos'
    | '/perfil'
    | '/projetos'
    | '/register'
    | '/projetos/$id'
    | '/projetos/novo'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/meus-projetos'
    | '/perfil'
    | '/projetos'
    | '/register'
    | '/projetos/$id'
    | '/projetos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MeusProjetosRoute: typeof MeusProjetosRoute
  PerfilRoute: typeof PerfilRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-projetos': {
      id: '/meus-projetos'
      path: '/meus-projetos'
      fullPath: '/meus-projetos'
      preLoaderRoute: typeof MeusProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface ProjetosRouteChildren {
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MeusProjetosRoute: MeusProjetosRoute,
  PerfilRoute: PerfilRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
