/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetosRouteRouteImport } from './routes/projetos/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetarSenhaIndexRouteImport } from './routes/resetar-senha/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RecuperarSenhaIndexRouteImport } from './routes/recuperar-senha/index'
import { Route as RankingIndexRouteImport } from './routes/ranking/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as NotificacoesIndexRouteImport } from './routes/notificacoes/index'
import { Route as MeusProjetosIndexRouteImport } from './routes/meus-projetos/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes/index'
import { Route as ProjetosNovoRouteImport } from './routes/projetos/novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos/$id'
import { Route as AuthGithubSuccessRouteImport } from './routes/auth/github/success'
import { Route as AuthGithubEmailExistsRouteImport } from './routes/auth/github/email-exists'
import { Route as AuthGithubCompleteProfileRouteImport } from './routes/auth/github/complete-profile'

const ProjetosRouteRoute = ProjetosRouteRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetarSenhaIndexRoute = ResetarSenhaIndexRouteImport.update({
  id: '/resetar-senha/',
  path: '/resetar-senha/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaIndexRoute = RecuperarSenhaIndexRouteImport.update({
  id: '/recuperar-senha/',
  path: '/recuperar-senha/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRouteRoute,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesIndexRoute = NotificacoesIndexRouteImport.update({
  id: '/notificacoes/',
  path: '/notificacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusProjetosIndexRoute = MeusProjetosIndexRouteImport.update({
  id: '/meus-projetos/',
  path: '/meus-projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ProjetosRouteRoute,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjetosRouteRoute,
} as any)
const AuthGithubSuccessRoute = AuthGithubSuccessRouteImport.update({
  id: '/auth/github/success',
  path: '/auth/github/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubEmailExistsRoute = AuthGithubEmailExistsRouteImport.update({
  id: '/auth/github/email-exists',
  path: '/auth/github/email-exists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCompleteProfileRoute =
  AuthGithubCompleteProfileRouteImport.update({
    id: '/auth/github/complete-profile',
    path: '/auth/github/complete-profile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRouteRouteWithChildren
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/meus-projetos/': typeof MeusProjetosIndexRoute
  '/notificacoes/': typeof NotificacoesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/recuperar-senha/': typeof RecuperarSenhaIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/resetar-senha/': typeof ResetarSenhaIndexRoute
  '/auth/github/complete-profile': typeof AuthGithubCompleteProfileRoute
  '/auth/github/email-exists': typeof AuthGithubEmailExistsRoute
  '/auth/github/success': typeof AuthGithubSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/meus-projetos': typeof MeusProjetosIndexRoute
  '/notificacoes': typeof NotificacoesIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/recuperar-senha': typeof RecuperarSenhaIndexRoute
  '/register': typeof RegisterIndexRoute
  '/resetar-senha': typeof ResetarSenhaIndexRoute
  '/auth/github/complete-profile': typeof AuthGithubCompleteProfileRoute
  '/auth/github/email-exists': typeof AuthGithubEmailExistsRoute
  '/auth/github/success': typeof AuthGithubSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRouteRouteWithChildren
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/meus-projetos/': typeof MeusProjetosIndexRoute
  '/notificacoes/': typeof NotificacoesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/recuperar-senha/': typeof RecuperarSenhaIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/resetar-senha/': typeof ResetarSenhaIndexRoute
  '/auth/github/complete-profile': typeof AuthGithubCompleteProfileRoute
  '/auth/github/email-exists': typeof AuthGithubEmailExistsRoute
  '/auth/github/success': typeof AuthGithubSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projetos'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/configuracoes/'
    | '/dashboard/'
    | '/login/'
    | '/meus-projetos/'
    | '/notificacoes/'
    | '/perfil/'
    | '/projetos/'
    | '/ranking/'
    | '/recuperar-senha/'
    | '/register/'
    | '/resetar-senha/'
    | '/auth/github/complete-profile'
    | '/auth/github/email-exists'
    | '/auth/github/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/meus-projetos'
    | '/notificacoes'
    | '/perfil'
    | '/projetos'
    | '/ranking'
    | '/recuperar-senha'
    | '/register'
    | '/resetar-senha'
    | '/auth/github/complete-profile'
    | '/auth/github/email-exists'
    | '/auth/github/success'
  id:
    | '__root__'
    | '/'
    | '/projetos'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/configuracoes/'
    | '/dashboard/'
    | '/login/'
    | '/meus-projetos/'
    | '/notificacoes/'
    | '/perfil/'
    | '/projetos/'
    | '/ranking/'
    | '/recuperar-senha/'
    | '/register/'
    | '/resetar-senha/'
    | '/auth/github/complete-profile'
    | '/auth/github/email-exists'
    | '/auth/github/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetosRouteRoute: typeof ProjetosRouteRouteWithChildren
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MeusProjetosIndexRoute: typeof MeusProjetosIndexRoute
  NotificacoesIndexRoute: typeof NotificacoesIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
  RecuperarSenhaIndexRoute: typeof RecuperarSenhaIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ResetarSenhaIndexRoute: typeof ResetarSenhaIndexRoute
  AuthGithubCompleteProfileRoute: typeof AuthGithubCompleteProfileRoute
  AuthGithubEmailExistsRoute: typeof AuthGithubEmailExistsRoute
  AuthGithubSuccessRoute: typeof AuthGithubSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetar-senha/': {
      id: '/resetar-senha/'
      path: '/resetar-senha'
      fullPath: '/resetar-senha/'
      preLoaderRoute: typeof ResetarSenhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha/': {
      id: '/recuperar-senha/'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha/'
      preLoaderRoute: typeof RecuperarSenhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRouteRoute
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes/': {
      id: '/notificacoes/'
      path: '/notificacoes'
      fullPath: '/notificacoes/'
      preLoaderRoute: typeof NotificacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-projetos/': {
      id: '/meus-projetos/'
      path: '/meus-projetos'
      fullPath: '/meus-projetos/'
      preLoaderRoute: typeof MeusProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof ProjetosRouteRoute
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof ProjetosRouteRoute
    }
    '/auth/github/success': {
      id: '/auth/github/success'
      path: '/auth/github/success'
      fullPath: '/auth/github/success'
      preLoaderRoute: typeof AuthGithubSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/email-exists': {
      id: '/auth/github/email-exists'
      path: '/auth/github/email-exists'
      fullPath: '/auth/github/email-exists'
      preLoaderRoute: typeof AuthGithubEmailExistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/complete-profile': {
      id: '/auth/github/complete-profile'
      path: '/auth/github/complete-profile'
      fullPath: '/auth/github/complete-profile'
      preLoaderRoute: typeof AuthGithubCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjetosRouteRouteChildren {
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteRouteChildren: ProjetosRouteRouteChildren = {
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteRouteWithChildren = ProjetosRouteRoute._addFileChildren(
  ProjetosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetosRouteRoute: ProjetosRouteRouteWithChildren,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MeusProjetosIndexRoute: MeusProjetosIndexRoute,
  NotificacoesIndexRoute: NotificacoesIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
  RecuperarSenhaIndexRoute: RecuperarSenhaIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ResetarSenhaIndexRoute: ResetarSenhaIndexRoute,
  AuthGithubCompleteProfileRoute: AuthGithubCompleteProfileRoute,
  AuthGithubEmailExistsRoute: AuthGithubEmailExistsRoute,
  AuthGithubSuccessRoute: AuthGithubSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
